name: path_type
description: A zero cost path type
version: 0.2.0
repository: https://github.com/mcmah309/path_type

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  rust_core: ^0.5.0
  path: ^1.9.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
